### ISSUE TITLE
Sceener doesn't download all results??

### ISSUE THREAD

**Issue by dave-lanigan** [mariostoev/finviz#86] opened 2021-01-03 23:26 UTC
im using get_ticker_details() on the Screener class output and not getting all my results downloaded?

    out = Screener(filters=filters, table='Performance', order='price')

    print(len(out))
    print(len(out.get_ticker_details()))

the above code returns two different lengths

**Comment by jacobsteenhuysen** [comment] 2021-01-24 14:07
I have the same problem.

**Comment by johnjoo1** [comment] 2021-02-06 22:06
Same problem. It seems to be somewhat random on how many results it will return too.

**Comment by tombohub** [comment] 2021-02-18 18:10
Same thing here, it skipped the one page of results

**Comment by jacobsteenhuysen** [comment] 2021-02-18 18:11
Idk what’s wrong with it.

**Comment by tombohub** [comment] 2021-02-18 18:14
@jacobsteenhuysen  is it because finviz on pypi is not updated as in git?

**Comment by johnjoo1** [comment] 2021-02-18 18:14
The latest version of the package fixed this for me:
`pip install -U git+https://github.com/mariostoev/finviz`

The package version hosted in PyPi was the one that wasn't working for me.

**Comment by tombohub** [comment] 2021-02-18 18:15
@johnjoo1 are u getting `css_selector` error with latest version, on python3.8?

**Comment by johnjoo1** [comment] 2021-02-18 18:21
> @johnjoo1 are u getting `css_selector` error with latest version, on python3.8?

I am not. 

![image](https://user-images.githubusercontent.com/664720/108402932-015f6800-71d3-11eb-8b53-46ef31408dfc.png)

**Comment by jacobsteenhuysen** [comment] 2021-02-18 18:24
it's messed up for me too. idk what's wrong. tried to re pip install it.

**Comment by tombohub** [comment] 2021-02-18 18:26
@jacobsteenhuysen  are you using pypi or git version?

**Comment by jacobsteenhuysen** [comment] 2021-02-18 18:27
i even pip installed the

**Comment by jacobsteenhuysen** [comment] 2021-02-18 18:27
i just installed the git version. was using pip before. still no dice :(
the git version worked for you?

**Comment by tombohub** [comment] 2021-02-18 18:31
@jacobsteenhuysen  didn't try yet, I am installing it right now

**Comment by tombohub** [comment] 2021-02-18 18:40
@jacobsteenhuysen it's working with install from github

**Comment by johnjoo1** [comment] 2021-02-18 19:52
If you're using it in a Jupyter notebook, remember that you'll need to restart the kernel or reload the package (not just re-import the page) after you've installed the version from github.

**Comment by jacobsteenhuysen** [comment] 2021-02-18 20:01
ok everyone. johnjoo is right you need to pip unistall finviz and then you need to install it his way with git. it started working for my in vscode.

**Comment by jordanchapian** [comment] 2021-02-27 21:17
ref https://github.com/mariostoev/finviz/pull/73 -- You can experiment with the delay settings and verify that you are getting the expected number of results.

**Comment by d3an** [comment] 2021-03-31 17:44
Changes have been merged to ensure all results are getting downloaded. The issue is that FinViz has employed rate limiting via Cloudflare, so the instantaneous data retrieval via `asyncio` is no longer feasible without data loss. If you pip install from the git source, the data will be retrieved, but slower (expect something like 0.5 seconds * ticker count). 

```bash
$ pip install -U git+https://github.com/mariostoev/finviz
```

**Closed** 2021-03-31 17:45 UTC
