### ISSUE TITLE
Module 'finviz' has no attribute 'get_analyst_price_targets'

### ISSUE THREAD

**Issue by mmehrle** [mariostoev/finviz#36] opened 2020-01-26 17:08 UTC
I was just testing a few of the functions in my iPython notebook and got this:

AttributeError: module 'finviz' has no attribute 'get_analyst_price_targets'

Very strange - I copied the example in the tutorial and all of the other functions seem to work fine.

Any idea? I'm using the latest version - pulled it yesterday.

**Comment by mariostoev** [comment] 2020-01-26 18:35
The issue is due to the pip package not being update to the latest version that's on GitHub. The issue is fixed now, since I updated the package. 

To update the existing package to the latest (1.3.0) version do: `pip install finviz==1.3.0 `

**Comment by mmehrle** [comment] 2020-01-26 18:53
Shouldn't I go 'pip update' instead? Or do a pip remove first and then 
run the 1.3 install?

**Comment by mariostoev** [comment] 2020-01-26 18:54
oh, run `pip update` but check google for the exact command. My bad.

**Comment by mmehrle** [comment] 2020-01-26 19:05
pip install finviz --upgrade

After that I did a...

pip show finviz
Name: finviz
Version: 1.3.0
Summary: Unofficial API for finviz.com
Home-page: https://github.com/mariostoev/finviz
Author: Mario Stoev
Author-email: bg.mstoev@gmail.com
License: MIT
Location: /Users/michael/anaconda3/lib/python3.6/site-packages
Requires: urllib3, requests, aiohttp, cssselect, lxml

Unfortunately it's not working:

 >>> import finviz
 >>> finviz.get_analyst_price_targets('AAPL')

AttributeError: module 'finviz' has no attribute 'get_analyst_price_targets'

**Comment by xOxXakerxOx** [comment] 2020-02-03 11:54
> The issue is due to the pip package not being updated to the latest version that's on GitHub. The issue is fixed now, since I updated the package.
> 
> To update the existing package to the latest (1.3.0) version do: `pip install finviz==1.3.0 `

does not work: "AttributeError: module 'finviz' has no attribute 'get_analyst_price_targets'"

**Comment by mmehrle** [comment] 2020-02-03 12:19
Still not working:

MBP:~ michael$ pip show finviz
Name: finviz
Version: 1.3.0
Summary: Unofficial API for finviz.com
Home-page: https://github.com/mariostoev/finviz
Author: Mario Stoev
Author-email: bg.mstoev@gmail.com
License: MIT

MBP:~ michael$ python
Python 3.6.10 |Anaconda custom (64-bit)| (default, Jan  7 2020, 15:01:53) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import finviz
>>> finviz.get_analyst_price_targets('AMZN')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'finviz' has no attribute 'get_analyst_price_targets'
>>>

**Comment by verdoganai** [comment] 2020-04-03 10:28
any update? mine is also not working

**Comment by mmehrle** [comment] 2020-04-03 10:36
Yeah I never got a response to my comment on Feb 3rd and sort of gave up on it.

**Comment by mariostoev** [comment] 2020-04-12 20:47
@verdoganai 
@mmehrle 

I updated the package again. Can you do `pip install finviz==1.3.1` to update to the current version? Then check if the issue is resolved if you can use `get_analyst_price_targets` as such `from finviz import get_analyst_price_targets
`. Thank you and sorry for the delay.

**Comment by mmehrle** [comment] 2020-04-12 21:16
Works on my end;

 >>> from finviz import get_analyst_price_targets
 >>> get_analyst_price_targets('AMZN')
[{'date': '2020-01-31', 'category': 'Reiterated', 'analyst': 'Telsey 
Advisory Group', 'rating': 'Outperform', 'price_from': 2200, 'price_to': 
2350}, {'date': '2020-01-31', 'category': 'Reiterated', 'analyst': 
'Pivotal Research Group', 'rating': 'Buy', 'price_from': 2250, 
'price_to': 2450}, {'date': '2020-01-31', 'category': 'Reiterated', 
'analyst': 'Oppenheimer', 'rating': 'Outperform', 'price_from': 2040, 
'price_to': 2400}, {'date': '2020-01-31', 'category': 'Reiterated', 
'analyst': 'Monness Crespi & Hardt', 'rating': 'Buy', 'price_from': 
2250, 'price_to': 2650}, {'date': '2020-01-27', 'category': 
'Reiterated', 'analyst': 'The Benchmark Company', 'rating': 'Buy', 
'price_from': 2100, 'price_to': 2300}, {'date': '2020-01-16', 
'category': 'Reiterated', 'analyst': 'Morgan Stanley', 'rating': 
'Overweight', 'price_from': 2100, 'price_to': 2200}, {'date': 
'2020-01-10', 'category': 'Initiated', 'analyst': 'Bernstein', 'rating': 
'Mkt Perform', 'price_from': 0, 'price_to': 0}, {'date': '2019-12-03', 
'category': 'Initiated', 'analyst': 'Citigroup', 'rating': 'Buy', 
'price_from': 0, 'price_to': 0}, {'date': '2019-11-26', 'category': 
'Reiterated', 'analyst': 'Pivotal Research Group', 'rating': 'Buy', 
'price_from': 2500, 'price_to': 2100}, {'date': '2019-11-26', 
'category': 'Initiated', 'analyst': 'China Renaissance', 'rating': 
'Hold', 'price_from': 0, 'price_to': 1850}, {'date': '2019-10-25', 
'category': 'Reiterated', 'analyst': 'Oppenheimer', 'rating': 
'Outperform', 'price_from': 2100, 'price_to': 2040}, {'date': 
'2019-10-16', 'category': 'Reiterated', 'analyst': 'Credit Suisse', 
'rating': 'Outperform', 'price_from': 2225, 'price_to': 2400}, {'date': 
'2019-10-15', 'category': 'Reiterated', 'analyst': 'Goldman', 'rating': 
'Buy', 'price_from': 2400, 'price_to': 2350}, {'date': '2019-10-08', 
'category': 'Resumed', 'analyst': 'Wolfe Research', 'rating': 
'Outperform', 'price_from': 0, 'price_to': 0}, {'date': '2019-09-27', 
'category': 'Reiterated', 'analyst': 'Wells Fargo', 'rating': 
'Outperform', 'price_from': 2200, 'price_to': 2300}, {'date': 
'2019-09-23', 'category': 'Reiterated', 'analyst': 'Morgan Stanley', 
'rating': 'Overweight', 'price_from': 2300, 'price_to': 2200}, {'date': 
'2019-09-03', 'category': 'Reiterated', 'analyst': 'RBC Capital Mkts', 
'rating': 'Outperform', 'price_from': 2250, 'price_to': 2600}, {'date': 
'2019-08-02', 'category': 'Resumed', 'analyst': 'MKM Partners', 
'rating': 'Buy', 'price_from': 2240, 'price_to': 2350}, {'date': 
'2019-07-26', 'category': 'Reiterated', 'analyst': 'Pivotal Research 
Group', 'rating': 'Buy', 'price_from': 2750, 'price_to': 2615}]
 >>>

**Comment by verdoganai** [comment] 2020-04-12 22:19
It is working. Thanks!

**Closed** 2020-04-13 13:08 UTC
